### ISSUE TITLE
What type of plastic is recommended for printing the parts?

### ISSUE THREAD

**Issue by Tobio89** [dschil138/Fulcrum#10]
Hi, wondering what plastic type you've used for printing the parts.
Do you use the same plastic for the angled keycaps too?

**Comment by dschil138** [comment]
I printed all mine in PLA+, including the keycaps. The case you could probably print in pretty much anything you want. The keycaps tho you are gonna have to do in something that prints well and you have a lot of control/experience with, because they are definitely a lot more difficult.
