### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [dschil138/Fulcrum#4]
Hello!

I found this project from https://hackaday.com/2023/02/04/fulcrum-foils-finger-fatigue/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and design files in any purpose?
It would be great to see any popular open source license.

**Comment by dschil138** [comment]
Oh wow I had no idea it got featured there, that's awesome.

Yeah i will take a look at some licenses and try to add one before the end of the day today. It will definitely be some sort of open source type license, I'm just not super familiar with all the options.

**Comment by dschil138** [comment]
Actually, maybe you or someone else here can help me with this - I don’t know a lot about the licensing stuff tbh

Right now, the only firmware files in the repo are for KMK firmware. They use GPLv3 license - does that mean I have to use the same?

Going forward, I also plan to add files for QMK and ZMK. QMK uses the same GPLv3 license, but ZMK uses MIT. Does that cause any issues or conflicts?

Do I have to pick one license for the whole repo? Sounds complicated to be doing multiple licenses.

**Comment by vazhnov** [comment]
Hmm.
If the GPL v3 code is separate with your code, then you probably can choose any license, just mention that KMK firmware is GPL v3.
But if your code is **based on** GPL v3 code, you probably should use GPL v3 for the whole project.

Please take a look at [GPL: Linking and derived works](https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works).

MIT is one of the most permissive licenses, you can do almost everything you want. Just read the MIT license text, it is short and clear.

**Comment by dschil138** [comment]
OK,  I added it as GPLv3, just for sake of simplicity. The code.py and kb.py file here are directly based on KMK, so I think it has to be that anyway.

Thanks for bringing this up! I really hadn't thought about it at all.

**Comment by vazhnov** [comment]
Thank you very much!
