### ISSUE TITLE
README typo (relegated vs regulated)

### ISSUE THREAD

**Issue by tannerntannern** [dschil138/Fulcrum#5]
Cool project.  I love this sentence from the README, but I believe it has a typo:
> Your two most capable fingers, both **regulated** to just one key - the space bar.

I believe "regulated" should be ["relegated"](https://www.dictionary.com/browse/relegated)

**Comment by dschil138** [comment]
ah, yep you're right. Good catch. Will fix in my next commit. I'll close this then so I don't forget. Thanks!

**Comment by dschil138** [comment]
Fixed on last commit. thanks again
