### ISSUE TITLE
Detailed wiring

### ISSUE THREAD

**Issue by Gerben1701** [dschil138/Fulcrum#7]
Hello dschil138,
I'm interested in building this, your opposable thumb control seems unique and definitely stands out!
I'm not much of a programmer (yet), but I know my way around CAD and a 3D printer; first step for me is building the 20-key version as-is and go from there, probably some remodelling then.
The wiring however seems incomplete or is it something standard I just don't know? Can you provide details or a reference?
Thanks for the share!

**Comment by dschil138** [comment]
Sure, I can definitely help you out there. Could you lmk how much background info you know on keyboard wiring already? Specifically if you are familiar with key matrix wiring? Don’t wanna give you a bunch of info you already know.

The current diagram is definitely incomplete. For the most part, the other side is just mirrored, and the rows are connected as if the whole thing is just one big keyboard (and not split). So it has 8 columns and 4 rows (including the 5-way switches)

The main purpose for the diagram was to illustrate how the top key is wired into the same row as the thumb keys, and to show how the 5-way switches are integrated. It does assume the user is familiar with key matrix wiring tho.

I can give you more info on that if you want, just want to understand which parts you are looking for clarification on

**Comment by Gerben1701** [comment]
That'd be great! This will be my first keyboard build and also my first arduino build. My background is in mechanical engineering, some electrical engineering and the occasional programming of PLCs, for fun I developed and build some analog guitar effects. As to keyboards, I only know the one basic: it's rows and columns... but I'm reading up on it.
For your build: Basically, how to wire up, connect which leads to which inputs? I think I should be able to figure it out from the code, but I really don't want to mess up :)

**Comment by dschil138** [comment]
Hey so I am still fine-tuning this, and will post a final version to the repo eventually, but here is a more complete guide for you.

![fulcrum-wiring-full (2)](https://user-images.githubusercontent.com/11950317/218586755-9777235f-c6fa-4484-ac11-7d081c10044d.jpg)

This is showing how the rows and columns would be wired to the GPIO pins currently spelled out in the 20-key version files in this repo, but you can really wire them to whatever inputs you want. Just change them accordingly in the kb.py file. You don't have to do exactly what I did here.

As for more general keyboard wiring questions, QMK has a pretty good handwiring guide [here ](https://docs.qmk.fm/#/hand_wire)which should help. There also some good videos on youtube if you look around there.

**Comment by Gerben1701** [comment]
Thanks very much!
That makes the instructions complete. 🙂
(Parts are ordered, ETA ranging from a few days to ~3 weeks. In the meantime printing and maybe iterating 3D parts.)
