### ISSUE TITLE
Wiring Diagram for the 40 key version

### ISSUE THREAD

**Issue by angel12** [dschil138/Fulcrum#9]
Do you have a wiring diagram (or even just a picture of the underside of the switches) for the 40 key version?

I'm about to start printing the case, and should be getting my microcontrollers within the next week or so, so I'll be ready to start wiring my board together here soon

**Comment by dschil138** [comment]
Hey so I don't have a diagram or anything for the 40 key version, as it's just a standard key matrix on that one. The reason i  made one for the 20-key version was that the rows are wired kind of oddly. But any standard key matrix handwiring explainer should do you fine when it come to the 40-key version. I did whip this drawing up for you real quick tho. Hope it helps!
![IMG_2560](https://user-images.githubusercontent.com/11950317/221467876-c03a4077-9a74-4e03-b159-810bc20361ab.jpg)

**Comment by angel12** [comment]
That gets me started. I've done a few handwires, just never one with a 5 way switch. Thanks!!

**Comment by dschil138** [comment]
Actually I just realized that drawing is little misleading when it comes to the 5-way switch. The row wire won't connect around to each connection like that. There is a "common" pin on the 5-way switch, and you only have to connect the wire to that one pin. The 20-key version diagram shows that part really well tho

Please let me know how your build goes! I'd love to see pics when you get there
